export const LOADING_USER = 'LOADING_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const GET_USER = 'GET_USER';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REDIRECT_USER_TO_AUTH = 'REDIRECT_USER_TO_AUTH';
export const  ADD_USER_DETAILS = ' ADD_USER_DETAILS';


