export const LOADING_DATA = 'LOADING_DATA';
export const GET_COURSES = 'GET_COURSES';
export const GET_All_COURSES = 'GET_All_COURSES';
export const GET_COURSES_BY_CATEGORIE = 'GET_COURSES_BY_CATEGORIE';
export const SET_ERRORS = 'SET_ERRORS';